
server:
  servlet:
    context-path: /api
spring:
  flyway:
    url: jdbc:h2:mem:hbasedb;DATABASE_TO_UPPER=false
    user: user
    password: zxcvbYe
    schemas:
      - flywayschema
    locations:
      - classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:hbasedb;DATABASE_TO_UPPER=false
    username: user
    password: zxcvbYe
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect